Fix mandos checks when calling invalid functions
ElrondNetwork/elrond-wasm-rs pull request #116
Opened 2021-02-04 15:16 UTC by claudiu725

2021-02-04 15:48 UTC, dorin-iancu submitted a review, later dismissed

2021-02-04 15:58 UTC, dorin-iancu approved these changes

2021-02-17 13:26 UTC, andrei-marinica requested changes

2021-02-17 13:26 UTC, andrei-marinica commented on mandos/src/logs.rs
> +	DefaultValue,
this needs more investigation and testing before we can merge

2021-03-18 20:30 UTC, andrei-marinica approved these changes

2021-03-18 23:19 UTC, merged