Local esdt and nft api
ElrondNetwork/elrond-wasm-rs pull request #176
Opened 2021-03-15 13:55 UTC by dorin-iancu

Implementation of Local Mint and Local Burn for Fungible (i.e. the legacy ESDT token type) hooks.
Implementation of ESDT as NFT API function hooks (issue, create, transfer etc.)

2021-03-15 14:44 UTC, sasurobert requested changes
looks good. needs implementation of bigIntGetESDTEXternalBalance and transferCreateRole

2021-03-15 18:14 UTC, sasurobert submitted a review, later dismissed
looks good. needs implementation of bigIntGetESDTEXternalBalance and transferCreateRole

2021-03-16 07:41 UTC, andrei-marinica submitted a review, later dismissed

2021-03-16 07:41 UTC, andrei-marinica commented on elrond-wasm/src/esdt.rs
> +		can_freeze: bool,
We should probably group all these arguments in a ESDTMetadata struct, but it is ok for now

2021-03-16 07:49 UTC, andrei-marinica approved these changes

2021-03-16 08:05 UTC, merged