Nft marketplace sft support
ElrondNetwork/elrond-wasm-rs pull request #251
Opened 2021-06-03 11:25 UTC by dorin-iancu

Some refactoring: splitting into modules and moving some code from endpoints into private functions.
SFTs with custom quantity are now supported. They can also be sold one at a time through a single auction.

2021-06-03 11:39 UTC, mateigraura commented on contracts/examples/esdt-nft-marketplace/src/auction.rs
> +}
format this

2021-06-03 12:11 UTC, andrei-marinica requested changes

2021-06-03 12:34 UTC, andrei-marinica approved these changes

2021-06-04 06:34 UTC, sasurobert approved these changes

2021-06-04 06:34 UTC, sasurobert commented on contracts/examples/esdt-nft-marketplace/src/lib.rs
> +		#[var_args] opt_sft_max_one_per_user: OptionalArg<bool>,
max_one_per_payment actually :)

2021-06-04 06:42 UTC, sasurobert approved these changes

2021-06-04 07:10 UTC, merged