receive multi transfer on callback
ElrondNetwork/elrond-wasm-rs pull request #354
Opened 2021-09-22 13:31 UTC by dorin-iancu

2021-09-23 07:28 UTC, andrei-marinica requested changes

2021-09-23 07:28 UTC, andrei-marinica commented on contracts/feature-tests/composability/forwarder/src/call_async.rs
> +    fn forward_async_retrieve_multi_transfer_funds(
Please move this to forwarder-raw, since it does not use the high-level proxies

2021-09-23 07:28 UTC, andrei-marinica commented on contracts/feature-tests/composability/forwarder/src/call_async.rs
> +    fn retrive_funds_multi_transfer_callback(&self, expected_nr_transfers: usize) -> SCResult<()> {
I think the raw callback in forwarder-raw already posts everything it receives in storage/logs. Maybe merge with that.

2021-09-29 13:30 UTC, alyn509 commented on contracts/feature-tests/composability/forwarder-raw/src/forwarder_raw.rs
> +    fn callback_payments(&self) -> VecMapper<(TokenIdentifier, u64, BigUint)>;
not critical, but more preferable to see a struct rather than a tuple of 3+ elements

2021-09-29 13:34 UTC, alyn509 approved these changes

2021-09-30 04:44 UTC, andrei-marinica approved these changes

2021-09-30 04:44 UTC, merged