Mandos esdt
ElrondNetwork/elrond-wasm-rs pull request #44
Opened 2020-11-09 13:01 UTC by dorin-iancu

ESDT support added to mandos tests + crowdfunding contract esdt example added

2020-11-09 16:23 UTC, andrei-marinica requested changes

2020-11-09 16:23 UTC, andrei-marinica commented on mandos/src/account.rs
> +pub enum CheckEsdt {
You can avoid having to use an extra Option, by having DefaultStar, same as with CheckValue. DefaultStar is identical to Star in behaviour, but it occurs when nothing is written in the json. They are separate just so we can reconstruct the mandos the other way around, no other function. DefaultStar would be the Option::None.

2020-11-09 16:23 UTC, andrei-marinica commented on elrond-wasm-debug/src/execute_mandos.rs
> +				Some(CheckEsdt::Equal(eq)) => {
There is a Checkable trait, that is used precisely for this. Implementing Checkable for CheckEsdt gives you the "check" method, where you can move the checking logic, with the match and all.
The point is to have less code here, where there is already plenty, and have at least the checking done somewhere else.

2020-11-09 16:23 UTC, andrei-marinica commented on mandos/src/account.rs
> +}
You should also implement the Checkable trait here, it takes away code from other, more crowded places.

2020-11-10 07:18 UTC, dorin-iancu commented on elrond-wasm-debug/src/blockchain_mock.rs
> +			*esdt_balance >= *value,
Nope, that gives the following error: 
mismatched types
expected mutable reference `&mut num_bigint::BigUint`
               found reference `&num_bigint::BigUint`

2020-11-10 09:12 UTC, andrei-marinica approved these changes

2020-11-10 09:15 UTC, merged