Managed buffer static cache
ElrondNetwork/elrond-wasm-rs pull request #448
Opened 2021-11-10 15:28 UTC by andrei-marinica

2021-11-10 17:26 UTC, claudiu725 approved these changes

2021-11-10 17:41 UTC, alyn509 submitted a review, later dismissed

2021-11-10 19:58 UTC, claudiu725 requested changes

2021-11-10 19:58 UTC, claudiu725 commented on elrond-wasm/src/types/general/static_buffer.rs
> +pub trait Drop {
```suggestion
impl Drop for StaticBufferRef {
```
Note: after this change, some other rust tests will fail.

2021-11-11 10:15 UTC, claudiu725 approved these changes

2021-11-11 15:36 UTC, alyn509 commented on elrond-wasm/src/types/static_buffer/lockable_static_buffer.rs
> +// }
dead code

2021-11-11 15:38 UTC, alyn509 approved these changes

2021-11-11 15:41 UTC, merged