ManagedVec sort & deduplicate
ElrondNetwork/elrond-wasm-rs pull request #486
Opened 2021-12-02 11:03 UTC by alyn509

2022-12-21 18:33 UTC, claudiu725 requested changes

2022-12-21 18:33 UTC, claudiu725 commented on framework/base/src/types/managed/wrapped/cached_managed_buffer.rs
> +    .unwrap_or_else(|| M::error_api_impl().signal_error(b"Static cache is in use"))
Slightly misleading error message - this error can also occur when the static buffer is too small for loading the managed buffer (the limit is 10000 bytes at the moment) - see [try_lock_with_copy_bytes](https://github.com/ElrondNetwork/elrond-wasm-rs/blob/7cf42c8e03c8b0543a4ca51ebf028b5416166d9d/framework/base/src/types/static_buffer/lockable_static_buffer.rs#L39)

2022-12-21 18:37 UTC, claudiu725 commented on framework/base/src/types/managed/wrapped/cached_managed_buffer.rs
> +    .unwrap_or_else(|| M::error_api_impl().signal_error(b"Static cache is in use"))
```suggestion
    .unwrap_or_else(|| M::error_api_impl().signal_error(b"static cache too small or already in use"))
```

2022-12-22 08:15 UTC, claudiu725 approved these changes

2022-12-22 08:22 UTC, dorin-iancu submitted a review, later dismissed

2022-12-22 09:31 UTC, andrei-marinica requested changes

2022-12-22 09:31 UTC, andrei-marinica commented on framework/base/src/types/managed/wrapped/managed_vec.rs
> +    fn reinterpret_slice_mut<T1, T2>(from: &mut [T1], len: usize) -> &mut [T2] {
Also unsafe

2022-12-22 09:31 UTC, andrei-marinica commented on framework/base/src/types/managed/wrapped/cached_managed_buffer.rs
> +pub fn with_buffer_contents<M, R, F>(managed_buffer: &ManagedBuffer<M>, f: F) -> R
I would make this a method of ManagedBuffer. Easier to find.

2022-12-22 09:31 UTC, andrei-marinica commented on framework/base/src/types/managed/wrapped/cached_managed_buffer.rs
> +fn load_static_cache<M>(managed_buffer: &ManagedBuffer<M>) -> StaticBufferRef<M>
I would make this a method of ManagedBuffer. Easier to find.

2022-12-22 10:18 UTC, andrei-marinica submitted a review, later dismissed

2022-12-22 11:40 UTC, claudiu725 approved these changes

2022-12-22 12:03 UTC, merged