Multisig initial implementation
ElrondNetwork/elrond-wasm-rs pull request #53
Opened 2020-11-23 06:41 UTC by andrei-marinica

Contains:
- multisig initial implementation
- sc deploy api - ArgBuffer, CodeMetadata, hook wrapper
- a bugfix
- some tests

2020-11-24 16:00 UTC, sasurobert requested changes

2020-11-27 16:10 UTC, andrei-marinica commented on contracts/modules/elrond-wasm-module-users/src/lib.rs
> +	#[storage_get("user_id")]
the framework will make sure of this ... maybe I manage to do this next week

2020-11-27 16:11 UTC, andrei-marinica commented on contracts/examples/multisig/src/lib.rs
> +	fn deposit(&self) {}
There is no other way to feed egld into the contract. The contract is not payable, and this is the only payable function.
Will also have an event at some point.

2020-12-04 10:45 UTC, sasurobert submitted a review, later dismissed

2020-12-04 11:48 UTC, sasurobert approved these changes

2020-12-04 11:54 UTC, merged