managed vec get and get_mut
ElrondNetwork/elrond-wasm-rs pull request #552
Opened 2022-01-13 12:34 UTC by dorin-iancu

2022-01-13 12:38 UTC, alyn509 submitted a review, later dismissed

2022-01-13 17:38 UTC, andrei-marinica approved these changes

2022-01-13 17:44 UTC, andrei-marinica requested changes

2022-01-13 17:44 UTC, andrei-marinica commented on elrond-wasm/src/types/managed/managed_vec_ref.rs
> +    managed_vec: &'a mut ManagedVec<M, T>,
Might be slightly more efficient wasm-wise to only store the handle here.
I will investigate.

2022-01-14 22:38 UTC, andrei-marinica approved these changes

2022-01-15 10:24 UTC, merged