Various improvements
ElrondNetwork/elrond-wasm-rs pull request #594
Opened 2022-02-14 14:50 UTC by dorin-iancu

- new call_value `payment_as_tuple` method, that returns a tuple instead of constructing an `EsdtTokenPayment` struct
- improve `is_valid_esdt_identifier` implementation
- improve some SC examples to use the newest APIs and less dynamic allocation

2022-02-15 12:13 UTC, andrei-marinica requested changes

2022-02-15 12:13 UTC, andrei-marinica commented on elrond-codec/src/impl_for_types/impl_vec.rs
> +#![allow(clippy::transmute_undefined_repr)]
Only add this on the respective methods, not the entire crate, I think the warning can be useful.
I will investigate more if there are better solutions to the layout problem.

2022-02-17 12:11 UTC, catalinnnn approved these changes

2022-02-17 12:25 UTC, claudiu725 approved these changes

2022-02-17 12:32 UTC, merged