Eliminate managed type new
ElrondNetwork/elrond-wasm-rs pull request #602
Opened 2022-02-21 10:10 UTC by alyn509

2022-02-21 14:09 UTC, andrei-marinica requested changes

2022-02-21 14:09 UTC, andrei-marinica commented on elrond-wasm/src/types/managed/big_uint_operators.rs
> +                let other_handle = M::managed_type_impl().bi_new_handle(other as i64);
We need to use something based on `bigIntSetInt64` here.
One of the temporary handles can be used.

2022-02-21 14:09 UTC, andrei-marinica commented on elrond-wasm/src/types/managed/big_uint_operators.rs
> +                let other_handle = M::managed_type_impl().bi_new_handle(other as i64);
Same.
We need to use something based on `bigIntSetInt64` here.
One of the temporary handles can be used.

2022-02-21 14:09 UTC, andrei-marinica commented on elrond-wasm/src/types/managed/big_uint_operators.rs
> +                let other_handle = M::managed_type_impl().bi_new_handle(other as i64);
Same.
We need to use something based on `bigIntSetInt64` here.
One of the temporary handles can be used.

2022-02-21 14:09 UTC, andrei-marinica commented on elrond-wasm/src/types/managed/big_uint_operators.rs
> +                let other_handle = M::managed_type_impl().bi_new_handle(other as i64);
Same.
We need to use something based on `bigIntSetInt64` here.
One of the temporary handles can be used.

2022-02-21 14:09 UTC, andrei-marinica commented on elrond-wasm/src/types/managed/big_uint_operators.rs
> +                let other_handle = M::managed_type_impl().bi_new_handle(other as i64);
Same.
We need to use something based on `bigIntSetInt64` here.
One of the temporary handles can be used.

2022-02-21 14:09 UTC, andrei-marinica commented on elrond-wasm/src/types/managed/big_uint_operators.rs
> +                let other_handle = M::managed_type_impl().bi_new_handle(other as i64);
Same.
We need to use something based on `bigIntSetInt64` here.
One of the temporary handles can be used.

2022-04-18 13:16 UTC, andrei-marinica submitted a review, later dismissed

2022-04-18 13:26 UTC, claudiu725 approved these changes

2022-04-19 06:31 UTC, andrei-marinica approved these changes

2022-04-19 06:32 UTC, merged