Multisig tests
ElrondNetwork/elrond-wasm-rs pull request #677
Opened 2022-04-11 07:44 UTC by claudiu725

2022-04-26 06:50 UTC, dorin-iancu submitted a review, later dismissed

2022-04-28 06:46 UTC, andrei-marinica requested changes

2022-04-28 06:46 UTC, andrei-marinica commented on contracts/examples/multisig/tests/multisig_rust_test_v2.rs
> +    let source_adder = &mut adder_deploy(world, ic);
`ic` is part of `world`, so I don't think we need it as a separate argument

2022-04-28 06:46 UTC, andrei-marinica commented on contracts/examples/multisig/tests/multisig_rust_test_v2.rs
> +    let first_value: BigUint = 42u64.into();
Couldn't we actually only work with u64 or even u32 up to the contract proxy? There will unlikely be any big numbers in the test.

2022-04-28 06:46 UTC, andrei-marinica commented on contracts/examples/multisig/tests/multisig_rust_test_v2.rs
> +    signers: &[&Address],
Would probably be nice to group these arguments in a context object.

2022-04-28 06:46 UTC, andrei-marinica commented on elrond-codec/src/equivalent/codec_from.rs
> +pub auto trait CodecSelf {}
Would rename to `CodecFromSelf`.

2022-04-28 07:24 UTC, andrei-marinica approved these changes

2022-04-28 08:35 UTC, andrei-marinica approved these changes

2022-04-28 08:36 UTC, merged