Api handle refactor
ElrondNetwork/elrond-wasm-rs pull request #774
Opened 2022-07-01 12:46 UTC by claudiu725

2022-07-05 10:08 UTC, andrei-marinica requested changes

2022-07-05 13:36 UTC, dorin-iancu submitted a review, later dismissed

2022-07-05 14:25 UTC, claudiu725 commented on elrond-codec/src/try_static_cast.rs
> +    fn cast_or_signal_err<U: TryStaticCast>(self) -> U {
Done :+1:

2022-07-06 09:31 UTC, andrei-marinica approved these changes

2022-07-06 09:43 UTC, merged